name: Deploy to Lightsail Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS Lightsail
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            cd ~/Pretina-V2/backend  # Ensure this matches your path on the server
            git pull origin main
            npm install
            pm2 restart pretina-backend || pm2 start src/server.js --name "pretina-backend"
